# IF YOU CHANGE THIS FILE, BE SURE TO RESTART ANY RUNNING JEKYLL SERVE INSTANCES

# --- SITE DATA & SEO ----------------------------------------------------------

# Site's title
title: Recipes

# Short description
tagline: Recipes

# Longer description
description: Recipes

# Site's URL
url: https://www.domain.com

# --- COLLECTIONS --------------------------------------------------------------

collections:
 recipes:
  output: true
  permalink: /:title/

# --- DEFAULTS -----------------------------------------------------------------

# Set defaults for post types

# Ideally the [image] variable below would pull in [site.logo] defined above
# to keep the code DRY, but variable substitution doesn't seem to work here.

defaults:
  -
    scope:
      path: ""
      type: recipes
    values:
      layout: recipe

# --- BUILD SETTINGS -----------------------------------------------------------

markdown: kramdown

# host: xxx.xxx.xxx.xxx
# destination: /var/www/domain.com

# Minifier settings
compress_html:

  # More aggressive
  # clippings: all

  # Less aggressive
  blanklines: true

  # Remove comments
  comments:  ["<!-- ", " -->"]

  # ignore:
  # envs: [development]

sass:
  sass_dir: style
  style: compressed

exclude:
  - README.md
  - docker-compose.yml
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
